# Generated by Django 5.2.5 on 2025-10-29 19:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgeunlock',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='badgeunlock',
            name='user',
        ),
        migrations.RemoveField(
            model_name='habitlog',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='habitlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='is_unwanted',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='points_per_completion',
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HabitEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('done', models.BooleanField(default=False)),
                ('earned_points', models.PositiveIntegerField(default=0)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='myapp.habit')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='BadgeUnlock',
        ),
        migrations.DeleteModel(
            name='HabitLog',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
